### ISSUE TITLE
Typo in HtmlEditorField_SelectUploadField.ss and SelectUploadField.ss causes default folders not to work

### ISSUE THREAD

**Issue by torleif** [silverstripe-labs/silverstripe-selectupload#24]
Line 16 in *Typo in HtmlEditorField_SelectUploadField.ss*:
```				<% else_if $canPreviewFolderx %>```
Should be 
```				<% else_if $canPreviewFolder %>```

And the same in *SelectUploadField.ss* on line 51:
```					<% else_if $canPreviewFolderx %>```

**Comment by tractorcow** [comment]
Thanks!
